### ISSUE TITLE
[WIKI BUG]: Image in Wiki is transparent

### ISSUE THREAD

**Issue by cirquit** [bmc-labs/board-mini#2]
**On which page is the problem?**
https://github.com/bmc-labs/board-mini/wiki/6.2-Wiring-Instructions

**Describe the bug or mistake**
Similar issue as with the README before - the image is transparent when using github dark mode.

**Screenshots**
![image](https://user-images.githubusercontent.com/9363632/113202346-efa9bf80-926a-11eb-876d-a6e7542aa2a7.png)

**Comment by cdbrkfxrpt** [comment]
thanks for the hint, fixed it :)
